### ISSUE TITLE
AoInput: Add prop for passing in instructional text

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#189]
## Issue Description
We should have a place to optionally pass in instructional text for an input.

![screen shot 2018-09-17 at 12 49 26 pm](https://user-images.githubusercontent.com/8300416/45637365-4cac4400-ba78-11e8-9c26-3b1638701941.png)

**Comment by ZainW** [comment]
closing since there is a pr merged
