### ISSUE TITLE
AoModal: Allow header-text to accept a String or a Number

### ISSUE THREAD

**Issue by tessakruger** [AmpleOrganics/Blaze.vue#203]
## Issue Description
Sometimes the modal title could contain only a number. For instance, if you're displaying an HTTP status code. Would like to update the headerText prop to accept types [String, Number].

## What is expected?
Clean console

## What is actually happening?
Vue warnings in console about Invalid prop type for 'headerText'. Expected String, got Number.

**Comment by ZainW** [comment]
i think text should be strings, if people feel differently let me know

ideally you would just string interpolate the number
