### ISSUE TITLE
AoInput: Create prop for rendering a search input

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#211]
## Issue Description
Currently there is no search-specific version of AoInput, which their should be. To kick it off, it should look like the current version used in Seed to Sale

<img width="220" alt="screen shot 2018-10-08 at 10 12 29 am" src="https://user-images.githubusercontent.com/8300416/46614048-dcc33380-cae2-11e8-9e56-3ac5fa6fd078.png">

**Comment by ZainW** [comment]
idk how relevant this is anymore, if this should be added as a feature please make a feature request
