### ISSUE TITLE
AoRadio: root class should be ao-radio

### ISSUE THREAD

**Issue by sarngru** [AmpleOrganics/Blaze.vue#213]
## Issue Description
The root css class on AoRadio is named `ao-checkbox`. It should be `ao-radio`.

## Vue and Node Version
N/A

## Steps to Reproduce
Inspect source of an AoRadio component. See below line in source code
https://github.com/AmpleOrganics/Blaze.vue/blob/9ceb64c5ce721567d840e3373ce7d9329c39a817/src/components/AoRadio.vue#L2

## What is expected?
Root css class should be `ao-radio`

## What is actually happening?
Root css class is `ao-checkbox`

**Comment by ZainW** [comment]
@Whapow another one if you want it

**Comment by ZainW** [comment]
make sure any docs/tests are updated if necessary

**Comment by Whapow** [comment]
@ZainW 
Are the radio buttons expected to remain vertical as part of this change?
