### ISSUE TITLE
AoInput, AoSelect, AoFileUpload, AoTextarea: Add slot for passing in a button

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#214]
## Issue Description
It would be handy to have a slot that we could pass a button in to so that we could easily achieve something like this:

![screen shot 2018-10-15 at 10 13 10 am](https://user-images.githubusercontent.com/8300416/46956303-f1fc0d00-d062-11e8-9821-ba6aab12dd91.png)

Requirements:
- Button goes to the right of the input
- Button is below the label
- Foolproof responsiveness. If the button has to wrap (smaller screen sizes) it does so by going below the input and still has adequate vertical spacing
- The text below the input does not go underneath the button. Ie. it is in the same enclosing div as the input
- As such, when the button wraps below the input, it would go below that text as well

**Comment by ZainW** [comment]
closed a similar one to this.

basically just use some sort grid to make this happen

**Comment by busheikin** [comment]
Can you link the similar one? I think saying "basically just use some sort grid to make this happen" is reductive. grids are for layout based on dividing available width into proportional columns, not for just placing any elements next to each other - though it could work here. 
Plus this has requirements regarding vertical spacing that are not considered by our horizontal grid. Ie. allow for adequate spacing between label and button in collapsed sizes, without using a solution that affects vertical spacing at non-collapsed sizes

**Comment by ZainW** [comment]
This can be done by adding a flex container though? unless the margin on either element is incorrect ie the spacing is wrong, if this is true then we likely need to figure something out. since we arent really mobile 

for now we dont include any grid like styling/components to do so.

 if this is an issue make it one as a seperate but just putting slots as the answer is likely not the way to go

**Comment by busheikin** [comment]
it needs to be inside the input component: below the input label, beside the input+info text. 
We can pick this up again when the time comes
