### ISSUE TITLE
AoInput - Allow type of month

### ISSUE THREAD

**Issue by Boshes** [AmpleOrganics/Blaze.vue#220]
## Issue Description
For HTML5 date input fields where the day does not matter, it would be ideal to have the input type allowed for month. This could be useful for report generation or date selection for a month's range.

## Vue and Node Version
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month

## What is expected?
The user will use the date input field and be presented with a date input selection spanning months so they know it's month selection

## What is actually happening?
The user will use the date input field and choose days in specific that are meaningful to the user but will not translate to what the actual purpose of the input field does

**Comment by ZainW** [comment]
you are be able to just add whatever html based attribute you want to input
