### ISSUE TITLE
AoTable: .ao-form-group should not have a bottom margin if it's the only thing in a cell

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#229]
.ao-form-group has a bottom margin applied to ensure proper vertical rhythm. However this is not necessary, and causes bad spacing, when form groups (ie inputs, selects) are in table fields.

We could say `.ao-table .ao-input .form-group: margin-bottom: 0` but that might be too overreaching.

**Comment by ZainW** [comment]
should be fixed by adding the table cell component, if not please reopen
