### ISSUE TITLE
AoRadio, AoCheckbox: Improve styles

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#232]
Some improvements needed to checkboxes and radios:
- Labels for radio options should not be bold.
- Positioning of the actual input element should be polished up
- Would be nice to have a single place to affect both checkbox and radio css since they are stylistically treated the same
- Need to fix the checkbox docs, changing the label text doesn't work

**Comment by ZainW** [comment]
if this is valid please make a pr, closing since it's old
