### ISSUE TITLE
AoInput, AoSelect, AoTextarea, AoFileUpload: Ability to have 'Mandatory' and 'Optional' fields

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#235]
Mostly thinking about a nice way to have fields marked as optional. This is considered best practice (as opposed to marking with an asterisk). Maybe this should just be done automatically if it is not specified as required.

**Comment by ZainW** [comment]
using proper labels and a validation library is the way to go for now unless we decide to bake in validations into our components
