### ISSUE TITLE
Maybe .ao-form-control should become .ao-input / .ao-select / .ao-textarea

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#24]
`.ao-form-control` was used only cause that's what the webapp uses, which is just a bootstrap remenant. We should change this to be .ao-input / .ao-select / .ao-textarea throughout the component and any instances of its use... OR SHOULD WE? Let's talk.

**Comment by ZainW** [comment]
please didnt talk about it so it's probably not important/relevant , feel free to reopen if anyone feels otherwise
