### ISSUE TITLE
AoButton: Remove the auto margin between buttons

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#241]
This causes style issues and probably doesn't actually provide any benefit.

``` 
& + &:not(.ao-btn--block) {
   margin-left: $spacer-micro;
 }
```

**Comment by ZainW** [comment]
make a pr if this is needed

**Comment by busheikin** [comment]
Oops I just deleted your comment Zain... brain fart.
You said "Closed cause it's old".
