### ISSUE TITLE
AoInput: Allow Step to be of type String as well

### ISSUE THREAD

**Issue by Boshes** [AmpleOrganics/Blaze.vue#244]
Please format your title as: `ComponentName: the issue`

## Issue Description

Number fields can also have `step` as `any` which doesn't show the hover text that HTML5 provides about the valid number ranges.

## Steps to Reproduce

- Create an ao-input with `step="any"`
## What is expected?

- It will record this prop to be any and not show hover text since it's `any`

## What is actually happening?

- It will not record this prop and cause warning/errors (the step ends up being defaulted to `any` or not present)

**Comment by ZainW** [comment]
non issue since we removed all html based properties to be added on their own
