### ISSUE TITLE
AoSelect: value prop should accept Booleans

### ISSUE THREAD

**Issue by tkilgour** [AmpleOrganics/Blaze.vue#272]
Please format your title as: `ComponentName: the issue`

## Issue Description

We have select boxes that contain "Yes" and "No" values. This should be represented by True/False, but AoSelect's 'value' prop does not allow Booleans.

## Steps to Reproduce

1. Set AoSelect values to `True` and `False`
2. Observe the following error in console:
```
 Invalid prop: type check failed for prop "value". Expected String, Number, got Boolean.
```

## What is expected?

AoSelect should allow all value types that native `<select>` allows, including Booleans.

## What is actually happening?

Prop type checking fails.

**Comment by martinlaws** [comment]
@wshanks01 should this issue be closed given the merged PR above?

**Comment by ZainW** [comment]
I asked @wshanks01 and he said we can close it
