### ISSUE TITLE
Variables: Desaturate the gray pallette

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#283]
# Component name

Not a component really. Looking at our colour palette here.
Design team is looking at changing the gray pallet to be fully desaturated - currently there is a slight blue tint.

## Components dependencies

We will need to consider how this will affect legacy app.

**Comment by ZainW** [comment]
This seems to not something that can be worked as a code issue at this point in time. if you have a pr to attain this then please make it
