### ISSUE TITLE
AoAlert: Enable clicking the alert to dismiss it

### ISSUE THREAD

**Issue by tessakruger** [AmpleOrganics/Blaze.vue#286]
# Feature request summary

The AoAlert currently has a timeout of 4 seconds before it disappears on its own. I'd like to see an option to include a 'clickToDismiss' or add a close 'X' action to dismiss/close the alert sooner than the 4 seconds.

## Rationale

There are times when you want the alert to disappear from view before the 4 seconds is up. Sometimes it's blocking certain tabs or breadcrumbs and you'd like to move it out of your way sooner than later. I feel that this would be a great UX improvement.

---

🌟 Feature requests that are not yet planned will be closed. We then use the issues [:+1: upvotes](https://help.github.com/articles/about-conversations-on-github/) to track and set priorities. See the [contribution guidelines](https://github.com/AmpleOrganics/Blaze.vue/blob/master/.github/CONTRIBUTING.md) for more information.

**Comment by ZainW** [comment]
This makes a lot of sense adding it to be worked on

**Comment by Whapow** [comment]
Change present on `f/dismiss-alert`, will create a PR once https://github.com/AmpleOrganics/Blaze.vue/pull/294 has been squashed & merged as this uses the material icons.
