### ISSUE TITLE
AoFileUpload: Add ability to select multiple files

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#291]
# Feature request summary

The `file` input type can allow multiple files to be selected, just needs `multiple` in the tag.

## Rationale

Not a ton of immediate benefit but I am working on something where uploading multiple files at once might make sense. This just moreso seems like base functionality considering it's a property of the actual file input HTML element

**Comment by ZainW** [comment]
If the only requirement is adding the `multiple` html attribute then this is already possible by passing it in as such using inherent attrs

**Comment by busheikin** [comment]
oh right duh
