### ISSUE TITLE
AoAlert: Give this a max-width instead of pct of screen width

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#299]
# Issue summary

The AoAlert is needlessly wide on larger screens because its width is 75% of screen width. It should just be fixed. Max-width: 700px

**Comment by Whapow** [comment]
@busheikin 
Would it be preferable to set a max-width of 75% and allow the alert to fit to content (with a min-width if desired), rather than having a fixed width? This would likely be better for mobile use.
