### ISSUE TITLE
/deep/ is being deprecated in chrome

### ISSUE THREAD

**Issue by ZainW** [AmpleOrganics/Blaze.vue#3]
get a warning on current chrome (Chrome 65) that /deep/ is being deprecated, 
not sure if it's the deep syntax

Possible Solution: use ```>>>``` which also is deep

edit: this may be a non issue O_O

**Comment by martinlaws** [comment]
@ZainW can this PR be closed given the merged PR above?

**Comment by ZainW** [comment]
Idk what that pr has to do with this issue but this issue is a non-issue

on build our pipeline converts the /deep/ properties that are needed from scss into the appropriate `>>>` handler in css so it's a non issue
