### ISSUE TITLE
AoInput: Label should be optional

### ISSUE THREAD

**Issue by sarngru** [AmpleOrganics/Blaze.vue#306]
# Issue summary
In some cases such as when using AoInput inside a AoTable label is not needed.

## Expected behavior
`label` prop should not be required

## Actual behaviour
`label` prop is required

## Specifications
- Blaze version number: All
- Browser: 
- Device:
- Operating System:

**Comment by ZainW** [comment]
we are keeping it as a required prop for accessibility, use the showLabel prop to hide the message if need be
