### ISSUE TITLE
Create tabs component

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#33]
Tabs provide more options for content navigation, and are currently  in use in the webapp.

Examples:
https://polaris.shopify.com/components/navigation/tabs#navigation
https://getbootstrap.com/docs/4.0/components/navs/#tabs

**Comment by ZainW** [comment]
we have a navbar currently that takes li's an transforms them into our style of navs, if this is insufficient please create a proposal by creating an issue
