### ISSUE TITLE
Create a button addon for input and selects

### ISSUE THREAD

**Issue by busheikin** [AmpleOrganics/Blaze.vue#54]
We should have the ability to easily create an input or a select with a button addon, so we don't have to manually put the two components together

![screen shot 2018-05-30 at 2 15 55 pm](https://user-images.githubusercontent.com/8300416/40739385-03ec7f24-6414-11e8-8209-ef56b8652d44.png)

**Comment by ZainW** [comment]
if this is still relevent please open a proposal, otherwise this should be handled through some sort of grid/css to arrange components imo
